Repository UCR-CS110-S23/project-novo, pull requests merged in 2023-06, with the labels that each got.

#55 Viviane9533/messaging
  components/MessageChat.jsx
  components/MessageResponse.jsx
  components/MyMessage.jsx
  components/NavBar.jsx
  pages/messaging.js
  public/messageGuy.jpg
  tailwind.config.js
Labels: Messages, Ready For Review, Frontend

#58 Viviane9533/messaging
  components/MessageResponse.jsx
  components/MyMessage.jsx
Labels: Messages, Frontend

#60 Viviane/popup
  components/MatchButtons.jsx
  public/ActivitySelected.png
Labels: Feed, Ready For Review, Frontend

#63 Profile Creation: Backend Working
  components/ActivityCards.jsx
  components/ActivityFeedCards.jsx
  components/CreateActivity.jsx
  components/ProgressBar.jsx
  components/Questions.jsx
  components/UserCard.jsx
  components/WelcomeLanding.jsx
  lib/hash.js
  pages/activityFeed.js
  pages/api/auth/createProfile.js
  pages/profileCreation.js
  public/activity1.png
Labels: Profile Creation, Frontend, Backend

#64 Another auth PR
  components/Questions.jsx
  components/UserCard.jsx
  pages/api/auth/[...nextauth].js
Labels: Backend, Authentication

#81 Activity Profile: Reviews & Ratings
  components/ActivityCards.jsx
  components/ActivityFeedCards.jsx
  components/Questions.jsx
  components/Review.jsx
  lib/getComments.js
  lib/getFeed.js
  package-lock.json
  package.json
  pages/activities/[aid].js
  pages/activityFeed.js
  pages/api/addReview.js
  pages/api/auth/[...nextauth].js
  pages/feed.js
Labels: Frontend, Backend, Activity Profile

#83 Cleanup
  components/ActivityCards.jsx
  components/NavBar.jsx
  components/WelcomeLanding.jsx
  pages/activities/[aid].js
  pages/feed.js
Labels: Ready For Review, Frontend, Backend

#84 Cleaned up editProfile + added hover effect to navBar
  README.md
  components/NavBar.jsx
  pages/api/hello.js
  pages/editProfile.js
  pages/messaging.js
  tailwind.config.js
Labels: Bugfix, Ready For Review

#85 more clean up
  components/ActivityCards.jsx
  components/ActivityFeedCards.jsx
  components/AddActivityPopUp.jsx
  components/MatchModal.jsx
  components/ProfilePicture.jsx
  components/Review.jsx
  components/WelcomeLanding.jsx
  lib/mongodb.js
  pages/activities/[aid].js
  pages/activityFeed.js
  pages/api/addReview.js
  pages/editProfile.js
  pages/feed.js
  pages/index.js
Labels: Bugfix, Ready For Review

#88 COMMENTS DONEE
  components/Review.jsx
  lib/getComments.js
  package-lock.json
  package.json
  pages/activities/[aid].js
Labels: Frontend, Backend, Activity Profile

#86 fixed link errors in activities pages + more ui pizzazz
  components/NavBar.jsx
  pages/activities/[aid].js
  pages/editProfile.js
  public/data/Activities.js
Labels: Bugfix, Ready For Review

#90 filters out logged in users from feed + ui touches
  pages/activities/[aid].js
  pages/feed.js
  public/data/Activities.js
Labels: Feed, Frontend, Backend

#94 Removed Google on Landing
  components/WelcomeLanding.jsx
Labels: Landing, Frontend
